# Generated by Django 3.1.2 on 2020-12-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_full_name', models.CharField(max_length=128, null=True)),
                ('stock_name', models.CharField(max_length=128, null=True)),
                ('threshold_low', models.FloatField(blank=True, null=True, verbose_name='Lower threshold alert')),
                ('threshold_high', models.FloatField(blank=True, null=True, verbose_name='Upper threshold alert')),
                ('send_update', models.BooleanField(verbose_name='send update')),
                ('last_update_sent', models.IntegerField(blank=True, default=0, null=True, verbose_name='last_update_sent')),
                ('customer_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
            ],
        ),
    ]
