# Generated by Django 3.1.2 on 2021-01-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_userstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='last_update_sent_high',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='last_update_sent_high'),
        ),
    ]
